# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Magnet' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Magnet

  target 'MagnetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MagnetWidget' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagnetWidget
  pod 'SwiftSerializer', '~> 0.6'

end
