# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.80.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # Grab the version number and the last build number on TestFlight so we can auto increment
    version = get_version_number(xcodeproj: "magnet.xcodeproj")
    build_number = latest_testflight_build_number(
      version: version,
      initial_build_number: 0
    ) + 1

    increment_build_number(
      build_number: build_number,
      xcodeproj: 'magnet.xcodeproj'
    )

    # Compile and build .xcarchive
    gym(
      scheme: "magnet",
      use_legacy_build_api: true  
    ) 

    # Upload the build to TestFlight
    pilot(
      skip_submission: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
